Repository phel-lang/phel-lang.org, pull requests merged in 2025-09, with the labels that each got.

#128 feat: index `contents/documentation/` for search along API
  build/src/php/FileGenerator/Application/ApiSearchGenerator.php
  build/tests/php/FileGenerator/Domain/ApiSearchGeneratorTest.php
  static/search.js
  templates/header.html
Labels: enhancement

#129 feat: semicolon comment syntax highlighting for website
  syntaxes/phel.sublime-syntax
Labels: enhancement

#127 Multi-arity function arguments
  content/documentation/functions-and-recursion.md
Labels: documentation

#126 Semicolon and inline s-expression comments
  content/documentation/basic-types.md
Labels: documentation

#136 Fix `/documentation` url
  content/documentation/_index.md
  templates/section.html
Labels: bug
